### ISSUE TITLE
Density matrix seems to be conjugated

### ISSUE THREAD

**Issue by jackyko8** [Strilanc/Quirk#423] opened 2019-03-16 22:58 UTC
It seems to me the the density matrix is conjugated, i.e. non-real elements flipped vertically.

For example, the density matrix for SH|0> is 1/2(|0><0|-i|0><1|+i|1><0|+|1><1|) based on my calculation, but Quirk shows 1/2(|0><0|+i|0><1|-i|1><0|+|1><1|).

I've done four test cases, SH, TH, SH(x)SH, S^(-1)H(x)SH, which are documented here:
http://qtol.jackykou.com/talk/Quirk%20Density%20Matrix%20Issue.pdf

Did I miss something?

Thanks.
Jacky

**Comment by Strilanc** [comment] 2019-03-20 01:25
You're right. I reproduced using numpy:

```python
import numpy as np
ket_a = np.array([[1], [1j]]) / np.sqrt(2)
print("ket")
print(ket_a)

bra_a = np.conj(np.transpose(ket_a))
density_a = np.dot(ket_a, bra_a)
print("density")
print(density_a)
```

Result:

```
ket
[[0.70710678+0.j        ]
 [0.        +0.70710678j]]
density
[[0.5+0.j  0. -0.5j]
 [0. +0.5j 0.5+0.j ]]
```

Which has the -i in the top right, whereas quirk puts it in the bottom left:

![image](https://user-images.githubusercontent.com/79941/54652487-47a26e80-4a74-11e9-8ee4-197927ce9c60.png)

**Comment by jackyko8** [comment] 2019-03-20 02:28
Thanks for looking into it.

**Comment by Strilanc** [comment] 2019-03-23 20:47
Fixed in https://github.com/Strilanc/Quirk/pull/404/commits/5d2b332c69e358fb71c0ecba9da6c25e54b3ff81 . Will be in next release.

**Comment by jackyko8** [comment] 2019-03-24 01:32
Thanks! Looking forward to the next release.

**Comment by jackyko8** [comment] 2019-03-25 07:52
Thanks for the release of v2.2. I like the explicit "S" gate.

On the Density Matrix, I can see that the caption has been changed but it looks to me that the amplitudes are the same as before. Could you please have another look?

**Comment by Strilanc** [comment] 2019-03-25 07:57
Bah, I think I transposed it in a second place and forgot to untranspose it in the first..

**Comment by Strilanc** [comment] 2019-08-12 23:09
The issue was that I fixed it in the multi-qubit density matrix display but not in the single-qubit density matrix display:

![image](https://user-images.githubusercontent.com/79941/62904426-aecf0100-bd3c-11e9-9ea3-9f9390fec6cc.png)

They're implemented using different mechanisms because there's higher performance code for the single-qubit case (because every circuit needs all the single-qubit density matrices for the displays at the end).

Fixed in https://github.com/Strilanc/Quirk/pull/438/commits/b7add27be94471806a3ac26068c1ae8cad24530e

**Closed by Strilanc** 2019-08-12 23:09 UTC
