### ISSUE TITLE
Encountered error: Error: c: malformed URI sequence in src/main.js

### ISSUE THREAD

**Issue by akvadrako** [Strilanc/Quirk#81] opened 2016-05-02 15:33 UTC
Hello Strilanc,

it was mostly working well enough for me, but when trying to return to a url via my history I got a another error.

URL
http://algorithmicassertions.com/quirk#circuit={%22cols%22:[[%22X%22,%22%E2%80%A2%22,%22X%22],[1,%22X^%E2%85%93%22,%22X^%E2%85%93%22],[1,1,%22X^%E2%85%93%22],[%22Bloch%22,%22Bloch%22,%22Bloch%22],[1,%22%E2%80%A2%22,%22%E2%80%A2%22,%22X%22],[1,%22%E2%97%A6%22,%22%E2%97%A6%22,%22X%22]]}

BROWSER USER AGENT
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:38.0) Gecko/20100101 Firefox/38.0

ERROR OBJECT
Error: c: malformed URI sequence in src/main.js

ERROR LOCATION
H@src.min.js:957:1
I@src.min.js:958:29
@src.min.js:960:53
g.prototype.getUncoatedModule@src.min.js:23:13
r.get@src.min.js:28:49
@src.min.js:1607:89

**Comment by Strilanc** [comment] 2016-05-02 16:35
Thanks for the report. Looks like an escaping issue, where Quirk tried to read the escaped %22s and such directly instead of as the character they represent.

I've been relying on the browser to do the escaping and unescaping. I'll add code that unescapes before parsing if needed.

Updating your browser may work around this issue for you. When I go to the link it works, but I have the latest version of Firefox instead of the v38 mentioned in the report.

**Comment by Strilanc** [comment] 2016-05-03 08:31
Hm, the code did call decodeURIComponent already. So I'm not exactly sure why it's failing.

https://github.com/Strilanc/Quirk/pull/87/commits/df299a2022951878287587e0a1e47507ce9fa7c3 and https://github.com/Strilanc/Quirk/pull/88/commits/38c4e302dcfb8d2dae8825f8b120e5ac575e9202 don't resolve this issue, but will improve the fallback.

The exception is now a 'recovered from' instead of a 'totally unexpected'. The drawing shouldn't break anymore when it happens. Also the generated details will include the value of document.location.hash, since the browser's exact interpretation of that is relevant.

**Comment by Strilanc** [comment] 2016-05-03 09:24
Okay, I've confirmed this is a bug in firefox. It was fixed in version 41. From [the release notes](https://developer.mozilla.org/en-US/Firefox/Releases/41#Miscellaneous):

> - The [URLUtils.hash](https://developer.mozilla.org/en-US/docs/Web/API/URLUtils/hash) property no longer decodes URL fragment ([bug 1093611](https://bugzilla.mozilla.org/show_bug.cgi?id=1093611)).

Since it's a browser issue, there's not a lot I can do to fix it. I think the correct fix is to ask you to update your browser. If it still doesn't work after updating your browser, re-open this issue.

**Closed by Strilanc** 2016-05-03 09:24 UTC
