### ISSUE TITLE
Spurious reporting of failure percentages

### ISSUE THREAD

**Issue by NoLongerBreathedIn** [Strilanc/Quirk#405] opened 2018-06-13 03:32 UTC
[This](http://algassert.com/quirk#circuit={%22cols%22:[[1,%22H%22,%22H%22,%22H%22,%22H%22],[%22%E2%8A%96%22,%22Z%22,%22Z%22,%22Z%22],[%22Z^%C2%BC%22,%22Z^%C2%BC%22,%22Z^%C2%BC%22,%22Z^%C2%BC%22],[%22X%22,%22X%22,%22X%22,%22X%22,%22%E2%80%A2%22],[%22Z^%C2%BC%22,%22Z^%C2%BC%22,%22Z^%C2%BC%22,%22Z^%C2%BC%22],[1,%22%E2%80%A2%22,%22X%22,%22X%22],[1,1,%22Z%22,1,%22X^-%C2%BD%22],[1,1,1,1,1,%22H%22,%22H%22,%22H%22,%22H%22],[1,1,1,1,%22%E2%8A%96%22,%22Z%22,%22Z%22,%22Z%22,%22Z%22],[1,1,1,1,%22Z^%C2%BC%22,%22Z^%C2%BC%22,%22Z^%C2%BC%22,%22Z^%C2%BC%22,%22Z^%C2%BC%22],[1,1,%22%E2%80%A2%22,1,%22X%22,%22X%22,%22X%22,%22X%22,%22X%22],[1,1,1,1,%22Z^%C2%BC%22,%22Z^%C2%BC%22,%22Z^%C2%BC%22,%22Z^%C2%BC%22,%22Z^%C2%BC%22],[1,1,1,%22%E2%80%A2%22,%22X%22,%22X%22,%22X%22,%22X%22,%22X%22],[1,1,1,1,%22Z^%C2%BC%22,%22Z^%C2%BC%22,%22Z^%C2%BC%22,%22Z^%C2%BC%22,%22Z^%C2%BC%22],[1,1,%22%E2%80%A2%22,1,%22X%22,%22X%22,%22X%22,%22X%22,%22X%22],[%22H%22,%22H%22,%22H%22,%22H%22],[%22Measure%22,%22Measure%22,%22Measure%22,%22Measure%22],[%22%E2%80%A2%22,%22X%22,%22X%22,%22X%22],[1,%22|0%E2%9F%A9%E2%9F%A80|%22],[1,1,%22|0%E2%9F%A9%E2%9F%A80|%22],[1,1,1,%22|0%E2%9F%A9%E2%9F%A80|%22,%22Amps1%22,%22Amps1%22,%22Amps1%22,%22Amps1%22,%22Amps1%22]]}) shows that the second postselect fails all the time, but the third somehow fails half the time as well?
Something's wrong here.
(Technically, nothing's horribly wrong [the circuit still fails all the time, which it should], but something seems to be off.)
(This fails on even the newest dev build, too — I checked.)

**Comment by Strilanc** [comment] 2018-06-13 03:51
Thanks for the report.

This is somewhat of a known issue. The problem is that, when you do a really strong postselection, all that's left in the state vector is floating point error. And so the later displays may be telling you about the error instead of about the state. In this case, 50% of the error vector makes it through that second post-selection.

One way to solve this would be to, at every step where there is a display, compute the total squared magnitude and see if it has gone below threshold. This has some performance implications, but not too bad. But it still wouldn't solve the harder problem, which is to get things right consistently when the displays are controlled.

**Comment by NoLongerBreathedIn** [comment] 2018-06-13 17:00
I figured that was the issue. The weird part is, the final displays still say NaN.

**Comment by Strilanc** [comment] 2018-06-14 11:48
Amplitude displays are far more sensitive to error than the other displays because the amplitude displays require tensor-factoring the state, whereas the others just require adding up density matrices or probabilities. They are much more prone to misclassify pure-vs-not-pure and nan-vs-not-nan as a result.

**Comment by Strilanc** [comment] 2018-07-18 06:07
I've been thinking more about this, and I think the trick here is to move away from hard cutoffs and instead do a continuous cross-fade of sorts. Same for the decoherence check.

**Comment by Strilanc** [comment] 2019-03-24 04:55
Fixed by https://github.com/Strilanc/Quirk/pull/404/commits/3ad0ce5a44cf103252a2f9b9ad9f2e90dca17ebf . Will be in next release.

**Closed by Strilanc** 2019-03-24 04:55 UTC
