### ISSUE TITLE
Encountered error: Defaulted to an empty circuit. Failed to understand circuit from URL. (Unexpected token  in JSON at position 395)

### ISSUE THREAD

**Issue by moudrick** [Strilanc/Quirk#432] opened 2019-05-07 07:53 UTC
Custom gate name accepts %20 (space) but does not accept %0A (new line).

Defaulted to an empty circuit. Failed to understand circuit from URL.

URL
https://algassert.com/quirk#circuit={%22cols%22:[[%22%E2%80%A6%22,%22~34qu%22,%22~lhdp%22],[1,%22~87lj%22,%22X%22],[%22%E2%80%A6%22,%22%E2%80%A6%22,%22%E2%80%A6%22],[%22%E2%80%A6%22,%22%E2%80%A6%22,%22%E2%80%A6%22],[%22Bloch%22,%22Bloch%22,%22Bloch%22],[%22Sample3%22],[%22%E2%80%A6%22,%22%E2%80%A6%22,%22%E2%80%A6%22],[%22X%22,%22X%22,%22X%22],[%22%E2%80%A6%22,%22%E2%80%A6%22,%22%E2%80%A6%22],[%22Sample3%22]],%22gates%22:[{%22id%22:%22~87lj%22,%22name%22:%22message%22,%22circuit%22:{%22cols%22:[[%22e^-iYt%22],[%22X^t%22]]}},{%22id%22:%22~f7c0%22,%22name%22:%22received%22,%22matrix%22:%22{{1,0},{0,1}}%22},{%22id%22:%22~34qu%22,%22name%22:%22State%20Flip0%22,%22matrix%22:%22{{1,0},{0,1}}%22},{%22id%22:%22~lhdp%22,%22name%22:%22State%0AFlip1%22,%22circuit%22:{%22cols%22:[[%22%E2%80%A6%22]]}}]}

BROWSER
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.108 Safari/537.36
Netscape
5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.108 Safari/537.36

RECOVERY DETAILS
{"document_location_hash": "#circuit={%22cols%22:[[%22%E2%80%A6%22,%22~34qu%22,%22~lhdp%22],[1,%22~87lj%22,%22X%22],[%22%E2%80%A6%22,%22%E2%80%A6%22,%22%E2%80%A6%22],[%22%E2%80%A6%22,%22%E2%80%A6%22,%22%E2%80%A6%22],[%22Bloch%22,%22Bloch%22,%22Bloch%22],[%22Sample3%22],[%22%E2%80%A6%22,%22%E2%80%A6%22,%22%E2%80%A6%22],[%22X%22,%22X%22,%22X%22],[%22%E2%80%A6%22,%22%E2%80%A6%22,%22%E2%80%A6%22],[%22Sample3%22]],%22gates%22:[{%22id%22:%22~87lj%22,%22name%22:%22message%22,%22circuit%22:{%22cols%22:[[%22e^-iYt%22],[%22X^t%22]]}},{%22id%22:%22~f7c0%22,%22name%22:%22received%22,%22matrix%22:%22{{1,0},{0,1}}%22},{%22id%22:%22~34qu%22,%22name%22:%22State%20Flip0%22,%22matrix%22:%22{{1,0},{0,1}}%22},{%22id%22:%22~lhdp%22,%22name%22:%22State%0AFlip1%22,%22circuit%22:{%22cols%22:[[%22%E2%80%A6%22]]}}]}"}

ERROR OBJECT
SyntaxError: Unexpected token 
 in JSON at position 395

ERROR LOCATION
SyntaxError: Unexpected token 
 in JSON at position 395
    at JSON.parse (<anonymous>)
    at o (https://algassert.com/quirk:363:206631)
    at l (https://algassert.com/quirk:363:514449)

**Comment by moudrick** [comment] 2019-05-07 08:16
possibly related:  #399 

https://github.com/Strilanc/Quirk/issues/399

**Comment by Strilanc** [comment] 2019-05-07 19:41
You need to escape the newline in order the JSON to be valid. You put a line break into the file data instead of into the encoded data. Use the text `\n` instead of the text `%0A`. For example:

```
https://algassert.com/quirk#circuit={"cols":[["~xx"]],"gates":[{"id":"~xx","name":"h\nx\ny\nz","circuit":{"cols":[["H", "X", "Y", "Z"]]}}]}
```

Which produces this result:

![image](https://user-images.githubusercontent.com/79941/57328038-3285ab80-70c5-11e9-8e02-70acc840afc1.png)

Though I won't guarantee that the visual style will stay consistent, since this is going outside what can be achieved within the UI.

Closing as this is not a bug.

**Closed by Strilanc** 2019-05-07 19:41 UTC
