### ISSUE TITLE
Annotate MSB and LSB for inputs on left of designer.

### ISSUE THREAD

**Issue by stellarpower** [Strilanc/Quirk#505] opened 2023-03-17 00:35 UTC
Thanks for this tool, really useful in debugging our own application.

Would it be possible to annotate the input state vectors on the left of the application wit their bit position?

We hit a few issues misreading which lines were the MSB and which were the LSB:

![image](https://user-images.githubusercontent.com/5004545/225782105-cd6b813d-d2e2-4933-b9a5-b092d181d70a.png)

Thanks!

**Comment by Strilanc** [comment] 2023-03-17 16:42
Quirk treats lower qubits as being more significant. For example, when showing kets like |abcd>, the d is the topmost qubit and the a is the bottommost qubit.

The reason things are ordered this way is because the arithmetic gates resize from the bottom, and because in my experience arithmetic circuits tend to be built in a way that makes it easiest to expand the circuit by adding a new most significant bit.

It wouldn't be unreasonable to annotate some of the arithmetic gates with bit significance indicators, but I'm not sure how to do it outside that context. The issue is that, although Quirk does have a particular preference, it doesn't literally prevent people from entering complex circuits that perform arithmetic but operate as if the top qubit was the least significant. And for a person entering a circuit like that, the annotations being backwards would be actively misleading. Any such global annotation would also fail to understand where the splits between registers were.

**Comment by Strilanc** [comment] 2023-11-09 21:25
Closing as wontfix. It's a reasonable idea but for now keeping the convention.

**Closed as completed by Strilanc** 2023-11-09 21:25 UTC
