### ISSUE TITLE
Encountered error: Defaulted to NaN results. Computing circuit values failed. (gl.getError() returned 1280 (?) after texImage2D.)

### ISSUE THREAD

**Issue by biswaroopmukherjee** [Strilanc/Quirk#98] opened 2016-05-05 07:42 UTC
Defaulted to NaN results. Computing circuit values failed.

URL
http://algorithmicassertions.com/quirk

BROWSER
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/601.5.17 (KHTML, like Gecko) Version/9.1 Safari/601.5.17
Netscape
5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/601.5.17 (KHTML, like Gecko) Version/9.1 Safari/601.5.17

RECOVERY DETAILS
{"circuitDefinition": {"cols": []}}

ERROR OBJECT
Error: gl.getError() returned 1280 (?) after texImage2D.

ERROR LOCATION
a@src.min.js:1458:88
_textureAndFramebufferInitializer@src.min.js:1445:2
src.min.js:1436:43
initializedValue@src.min.js:1401:81
initializedFramebuffer@src.min.js:1440:176
src.min.js:1411:96
renderTo@src.min.js:1425:139
src.min.js:742:129
renderTo@src.min.js:1425:139
zero@src.min.js:796:69
_fromCircuitAtTime_noFallback@src.min.js:783:87
fromCircuitAtTime@src.min.js:778:79
_computeStateForBucket@src.min.js:836:101
statsAtApproximateTime@src.min.js:837:201
F@src.min.js:947:151
src.min.js:960:65
getUncoatedModule@src.min.js:23:27
get@src.min.js:28:68
global code@src.min.js:1607:114

**Comment by Strilanc** [comment] 2016-05-05 12:25
Thanks for the report. Looks like an issue initializing the webgl code in Safari, possibly related to using float textures.

Could either be a feature not supported by your GPU (in which case I should give a better error, or support that case) or, more likely, me not calling the right things in the right order.

One really odd thing here is the '1280 (?)' part. 1280 is the error code for 'INVALID ENUM'. [Quirk knows this.](https://github.com/Strilanc/Quirk/blob/master/src/webgl/WglUtil.js#L23) The fact that it described the error as "?" instead of "INVALID_ENUM" could indicate that WebGLRenderingContext is missing properties I assumed it would always have and [MDN says it should have](https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/Constants#Errors).

**Comment by Strilanc** [comment] 2016-05-05 12:39
Meta fixes (but not actual fixes):

https://github.com/Strilanc/Quirk/commit/7567d17040becd37a014d2ca53a7bc3c67669ae6 should fix the ?-despite-known-code part of this issue (and also call out the fact that it had to do that).

I also added https://github.com/Strilanc/Quirk/commit/ab5dcba27a69b0b0dc9120ba4f4bebaba93fd661 in case this is masking a previous error that had more information.

**Comment by Strilanc** [comment] 2016-05-05 17:48
I have managed to reproduce this bug. Will investigate more.

**Comment by Strilanc** [comment] 2016-05-08 01:34
Fixed by https://github.com/Strilanc/Quirk/commit/0a598cda6ffe820748ff60c70196dfb503ab5ced

**Closed by Strilanc** 2016-05-08 01:34 UTC
