### ISSUE TITLE
Encountered error: Uncaught TypeError: Cannot read property 'y' of undefined

### ISSUE THREAD

**Issue by ChristopherElliott** [Strilanc/Quirk#419] opened 2018-12-09 21:57 UTC
Added two X gates, Removed first and it crashed.

URL
http://algassert.com/quirk#circuit={%22cols%22:[[%22X%22,%22X%22]]}

BROWSER
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.80 Safari/537.36
Netscape
5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.80 Safari/537.36

ERROR OBJECT
TypeError: Cannot read property 'y' of undefined

ERROR LOCATION
TypeError: Cannot read property 'y' of undefined
    at c._useControlsHintVisibility (http://algassert.com/quirk:340:457723)
    at c._drawHint_useControls (http://algassert.com/quirk:340:457779)
    at c._drawHint (http://algassert.com/quirk:340:455698)
    at c.paint (http://algassert.com/quirk:340:452675)
    at $traceurRuntime.createClass._triggerIdle.K [as action] (http://algassert.com/quirk:340:384275)
    at $traceurRuntime.createClass._triggerIdle._triggerIdle (http://algassert.com/quirk:340:68893)
    at $traceurRuntime.createClass._triggerIdle.trigger (http://algassert.com/quirk:340:69182)
    at http://algassert.com/quirk:340:384676
    at $traceurRuntime.createClass.observable.send (http://algassert.com/quirk:340:80678)
    at $traceurRuntime.createClass.observable.set (http://algassert.com/quirk:340:81076)

**Comment by Strilanc** [comment] 2018-12-11 21:13
I think this might be fixed in the dev version, but am not sure.

Could you describe *how* you removed the X gate? Was it by dragging off the left side of the screen?

**Comment by Strilanc** [comment] 2019-03-23 23:38
Closing for now because I'm not able to reproduce the issue, and there's been no followup on how to do so.

**Closed by Strilanc** 2019-03-23 23:38 UTC
